---
# handlers file for postfix

- name: Rebuild alias database
  ansible.builtin.command:
    cmd: postalias "{{ postfix_alias_path }}"
  changed_when: true

- name: Rebuild smtp_generic database
  ansible.builtin.command:
    cmd: postmap "{{ postfix_smtp_generic_path }}"
  changed_when: true

- name: Rebuild sender_access database
  ansible.builtin.command:
    cmd: postmap "{{ postfix_sender_access_path }}"
  changed_when: true

- name: Rebuild recipient_access database
  ansible.builtin.command:
    cmd: postmap "{{ postfix_recipient_access_path }}"
  changed_when: true

- name: Rebuild transport_maps database
  ansible.builtin.command:
    cmd: postmap /etc/postfix/transport
  changed_when: true

- name: Rebuild sasl_password_map database
  ansible.builtin.command:
    cmd: postmap {{ postfix_smtp_sasl_password_map }}
  changed_when: true

- name: Rebuild sender_dependent_relayhost_maps database
  ansible.builtin.command:
    cmd: postmap "{{ postfix_sender_dependent_relayhost_map_path }}"
  changed_when: true

- name: Rebuild sender_canonical_maps database
  ansible.builtin.command:
    cmd: postmap "{{ postfix_sender_canonical_map_path }}"
  changed_when: true

- name: Rebuild smtp_generic_maps database
  ansible.builtin.command:
    cmd: postmap "{{ postfix_smtp_generic_map_path }}"
  changed_when: true

- name: Validate configuration
  ansible.builtin.command:
    cmd: postconf
  changed_when: false

- name: Reload postfix
  ansible.builtin.service:
    name: "{{ postfix_service }}"
    state: reloaded

- name: Restart postfix
  ansible.builtin.service:
    name: "{{ postfix_service }}"
    state: restarted
